version: '2'
services:
  app:
    image: app
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
    volumes:
      - /Users/lukaszkusiak/Desktop/quest:/Users/lukaszkusiak/Desktop/quest
  mypostgres:
    image: postgres
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb
  front:
    build: /usr/share/ngnix/html
    container_name: angular
    ports:
      - 4200:80



